apiVersion: 0.2.0
environments:
  default:
    destination:
      namespace: default
      server: https://10.157.157.65:6443
    k8sVersion: v1.11.2
    path: default
  jinanpytorchenv:
    destination:
      namespace: jinanpytorch
      server: https://10.157.157.65:6443
    k8sVersion: v1.11.2
    path: jinanpytorchenv
kind: ksonnet.io/app
libraries:
  pytorch-job:
    name: pytorch-job
    registry: kubeflow
    version: 275abef578d170eb5bbc1d1b71c3bb2ecbad44b9
name: mypytorchapp
registries:
  incubator:
    protocol: github
    uri: github.com/ksonnet/parts/tree/master/incubator
  kubeflow:
    protocol: github
    uri: github.com/kubeflow/kubeflow/tree/master/kubeflow
version: 0.0.1
